### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by culajevic** [culajevic/labcube#2]
## TODO - Initial setup

* [x] Install npm
* [x] Install gulp
* [x] Create gulpfile.js
* [x] Create folder structure]
* [x] Create boilerplate
* [x] Git init
* [x] Set remote repository
